personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url 

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("projects.urls")),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}), 
]

if settings.DEBUG == False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.index, name='index'),   # root URL is hooked up to the project_index view.
        #path("<int:pk>/", views.project_detail, name="project_detail"), # Value passed in the URL is an integer named pk.
]

projects/models.py
from django.db import models

# About Me Section
class AboutMe(models.Model):
        name = models.CharField(max_length=20)
        profile_img = models.ImageField(upload_to='profile/')
        heading = models.CharField(max_length=50)
        career = models.CharField(max_length=20)
        description = models.TextField(blank=False)

        # Update when modified
        updated = models.DateTimeField(auto_now=True)

        def __str__(self):
                return self.career


# Social media links
class Profile(models.Model):
        about = models.ForeignKey(AboutMe, on_delete=models.CASCADE)
        social_name = models.CharField(max_length=10)
        social_link = models.URLField(max_length=200)


# Work Skills
class Category(models.Model):
        name = models.CharField(max_length=20)
        updated = models.DateTimeField(auto_now=True)

        class Meta:
                verbose_name = 'Skill'
                verbose_name_plural = 'Skills'
        
        def __str__(self):
                return self.name


class Skills(models.Model):
        category = models.ForeignKey(Category, on_delete=models.CASCADE)
        skill_name = models.CharField(max_length=20)


# Contains projects
class Project(models.Model):
        title = models.CharField(max_length=30)
        image = models.ImageField(upload_to='project_img/')
        link = models.URLField(max_length=200)

        def __str__(self):
                return f'Portfolio {self.id}'
 

projects/views.py
from django.shortcuts import render
from .models import AboutMe, Profile, Category, Skills, Project

def index(request):
        about = AboutMe.objects.latest('updated')
        profiles = Profile.objects.filter(about=about)

        categories = Category.objects.all()

        project = Project.objects.all()

        context = {
                'about': about,
                'profiles': profiles,
                'categories': categories,
                'project': project

        }

        return render(request, 'index.html', context)


#def project_index(request):
#        projects = Project.objects.all()        # query: allows to create, retrieve, update, or delete objects in your database.
#        context = {     # Dictionary that is used to send information to my template.
#                'projects': projects            
#        }
#        return render(request, 'project_index.html', context)  # Entries added to the context are available in the template.
#        
#
#def project_detail(request, pk):
#        project = Project.objects.get(pk=pk)    # query retrieves the project with primary key.
#        context = {     # Dictionary gets assigned the project
#                'project': project
#        }
#        return render(request, 'project_detail.html', context)  # Project will pass to render(). 

projects/templates/index.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Portfolio: Ryan Kellmer</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                <div>
                    <a href="#" class="nav__logo">Ryan Kellmer</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#about" class="nav__link">About Me</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Portfolio</a></li>
                        <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">
            <!--===== HOME =====
            <section class="home" id="home">
                <div class="home__container bd-grid">
                    <h1 class="home__title"><span>HE</span><br>LLO.</h1>

                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                    </div>

                    <img src="assets/img/perfil.png" alt="" class="home__img">
                </div>
            </section>
        -->
            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">{{about.name}}</h2>

                <div class="about__container bd-grid">
                    <div class="about__img">
                        <img src="{% static 'img/profile_pic.png' %}" alt="">
                    </div>

                    <div>
                        <h2 class="about__subtitle">{{about.heading}}</h2>
                        <span class="about__profession">{{about.career}}</span>
                        <p class="about__text">{{about.description}}</p>

                        <div class="about__social">
                            <a href="http://www.linkedin.com/in/ryan-kellmer-263667200/" class="about__social-icon"><i class='bx bxl-linkedin' ></i></a>
                            <a href="https://github.com/ryankellmer" class="about__social-icon"><i class='bx bxl-github' ></i></a>
                        </div>
                    </div>
                </div>
            </section>

            <!--===== SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Skills</h2>

                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        {% for category in categories %}
                            <h3 class="skills__subtitle">{{category.name}}</h3>
                            {% for skills in category.skills_set.all %}
                                <span class="skills__name">{{skills.skill_name}}</span>
                            {% endfor %}
                        {% endfor %}
                    </div>

                    <div class="skills__img">
                        <img src="{% static 'img/skill.jpg' %}" alt="">
                    </div>
                </div>
            </section>

            <!--===== PORTFOLIO =====-->
            <section class="portfolio section" id="portfolio">
                <h2 class="section-title">Portfolio</h2>

                <div class="portfolio__container bd-grid">
                    <div class="portfolio__img">
                        <img src="{% static 'img/project1.png' %}" alt="">

                        <div class="portfolio__link">
                            <a href="https://github.com/ryankellmer/BlueDragonsGame" class="portfolio__link-name">Blue Dragons Game</a>
                        </div>
                    </div>
                    <div class="portfolio__img">
                        <img src="{% static 'img/project2.png' %}" alt="">

                        <div class="portfolio__link">
                            <a href="https://github.com/ryankellmer/My-Portfolio" class="portfolio__link-name">Personal Portfolio</a>
                        </div>
                    </div>
                    <div class="portfolio__img">
                        <img src="{% static 'img/project3.png' %}" alt="">

                        <div class="portfolio__link">
                            <a href="https://github.com/ryankellmer/Project_5160" class="portfolio__link-name">Decision Tree Classifier</a>
                        </div>
                    </div>
                    <!--
                    <div class="portfolio__img">
                        <img src="{% static 'assets/img/work4.jpg' %}" alt="">

                        <div class="portfolio__link">
                            <a href="#" class="portfolio__link-name">View details</a>
                        </div>
                    </div>
                    <div class="portfolio__img">
                        <img src="{% static 'assets/img/work5.jpg' %}" alt="">

                        <div class="portfolio__link">
                            <a href="#" class="portfolio__link-name">View details</a>
                        </div>
                    </div>
                    <div class="portfolio__img">
                        <img src="{% static 'assets/img/work6.jpg' %}" alt="">

                        <div class="portfolio__link">
                            <a href="#" class="portfolio__link-name">View details</a>
                        </div>
                    </div>
                -->
                </div>
            </section>

            <!--===== CONTACT =====-->
            <section class="contact section" id="contact">
                <h2 class="section-title">Contact</h2>

                <div class="contact__container bd-grid">
                    <div class="contact__info">
                        <h3 class="contact__subtitle">EMAIL</h3>
                        <span class="contact__text">kellmer.ryan.j@gmail.com</span>

                        <h3 class="contact__subtitle">PHONE</h3>
                        <span class="contact__text">+1 760 646-3694</span>

                        <h3 class="contact__subtitle">Location</h3>
                        <span class="contact__text">Buena Park, CA 90621</span>
                    </div>
                    <!--
                    <form action="" class="contact__form">
                        <div class="contact__inputs">
                            <input type="text" placeholder="Name" class="contact__input">
                            <input type="mail" placeholder="Email" class="contact__input">
                        </div>

                        <textarea name="" id="" cols="0" rows="10" class="contact__input"></textarea>

                        <input type="submit" value="Enter" class="contact__button">
                    </form>
                    -->
                </div>
            </section>
        </main>

        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid">
                <div class="footer__data">
                    <h2 class="footer__title">Ryan Kellmer</h2>
                    <p class="footer__text">I'm Ryan Kellmer and this is my personal website</p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">EXPLORE</h2>
                    <ul>
                        <li><a href="#about" class="footer__link">About Me</a></li>
                        <li><a href="#skills" class="footer__link">Skills</a></li>
                        <li><a href="#portfolio" class="footer__link">Portfolio</a></li>
                        <li><a href="#Contact" class="footer__link">Contact</a></li>
                    </ul>
                </div>
            </div>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>